// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

namespace behaviac
{
	public class CompareValue_Situation : ICompareValue<Situation>
	{
		public override bool Equal(Situation lhs, Situation rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(Situation lhs, Situation rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(Situation lhs, Situation rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(Situation lhs, Situation rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(Situation lhs, Situation rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(Situation lhs, Situation rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_ActionStatus : ICompareValue<ActionStatus>
	{
		public override bool Equal(ActionStatus lhs, ActionStatus rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(ActionStatus lhs, ActionStatus rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(ActionStatus lhs, ActionStatus rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(ActionStatus lhs, ActionStatus rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(ActionStatus lhs, ActionStatus rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(ActionStatus lhs, ActionStatus rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_bVector3 : ICompareValue<bVector3>
	{
		public override bool Equal(bVector3 lhs, bVector3 rhs)
		{
			return (lhs.x == rhs.x) && (lhs.y == rhs.y) && (lhs.z == rhs.z);
		}
		public override bool NotEqual(bVector3 lhs, bVector3 rhs)
		{
			return !Equal(lhs, rhs);
		}
	}


	public class BehaviorLoaderImplement : BehaviorLoader
	{
		private class CMethod_behaviac_Agent_VectorAdd : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorAdd()
			{
			}

			public CMethod_behaviac_Agent_VectorAdd(CMethod_behaviac_Agent_VectorAdd rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorAdd(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorAdd((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorClear : CAgentMethodVoidBase
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorClear()
			{
			}

			public CMethod_behaviac_Agent_VectorClear(CMethod_behaviac_Agent_VectorClear rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorClear(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				behaviac.Agent.VectorClear((IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorContains : CAgentMethodBase<bool>
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorContains()
			{
			}

			public CMethod_behaviac_Agent_VectorContains(CMethod_behaviac_Agent_VectorContains rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorContains(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				_returnValue.value = behaviac.Agent.VectorContains((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorLength : CAgentMethodBase<int>
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorLength()
			{
			}

			public CMethod_behaviac_Agent_VectorLength(CMethod_behaviac_Agent_VectorLength rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorLength(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				_returnValue.value = behaviac.Agent.VectorLength((IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorRemove : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorRemove()
			{
			}

			public CMethod_behaviac_Agent_VectorRemove(CMethod_behaviac_Agent_VectorRemove rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorRemove(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorRemove((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_SoilderAgent_Attack : CAgentMethodBase<behaviac.EBTStatus>
		{
			IInstanceMember _target;

			public CMethod_SoilderAgent_Attack()
			{
			}

			public CMethod_SoilderAgent_Attack(CMethod_SoilderAgent_Attack rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_SoilderAgent_Attack(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_target = AgentMeta.ParseProperty<FightAgent>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_target != null);

				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((SoilderAgent)agent).Attack((FightAgent)_target.GetValueObject(self));
			}

			public override IValue GetIValue(Agent self, IInstanceMember firstParam)
			{
				Agent agent = Utils.GetParentAgent(self, _instance);

				FightAgent result = ((CInstanceMember<FightAgent>)firstParam).GetValue(self);
				_returnValue.value = ((SoilderAgent)agent).Attack(result);
				return _returnValue;
			}
		}

		private class CMethod_SoilderAgent_MoveTo : CAgentMethodBase<behaviac.EBTStatus>
		{
			IInstanceMember _targetPos;

			public CMethod_SoilderAgent_MoveTo()
			{
			}

			public CMethod_SoilderAgent_MoveTo(CMethod_SoilderAgent_MoveTo rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_SoilderAgent_MoveTo(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_targetPos = AgentMeta.ParseProperty<bVector3>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_targetPos != null);

				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((SoilderAgent)agent).MoveTo((bVector3)_targetPos.GetValueObject(self));
			}

			public override IValue GetIValue(Agent self, IInstanceMember firstParam)
			{
				Agent agent = Utils.GetParentAgent(self, _instance);

				bVector3 result = ((CInstanceMember<bVector3>)firstParam).GetValue(self);
				_returnValue.value = ((SoilderAgent)agent).MoveTo(result);
				return _returnValue;
			}
		}

		private class CMethod_SoilderAgent_MoveToTarget : CAgentMethodBase<behaviac.EBTStatus>
		{
			IInstanceMember _target;

			public CMethod_SoilderAgent_MoveToTarget()
			{
			}

			public CMethod_SoilderAgent_MoveToTarget(CMethod_SoilderAgent_MoveToTarget rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_SoilderAgent_MoveToTarget(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_target = AgentMeta.ParseProperty<FightAgent>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_target != null);

				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((SoilderAgent)agent).MoveToTarget((FightAgent)_target.GetValueObject(self));
			}

			public override IValue GetIValue(Agent self, IInstanceMember firstParam)
			{
				Agent agent = Utils.GetParentAgent(self, _instance);

				FightAgent result = ((CInstanceMember<FightAgent>)firstParam).GetValue(self);
				_returnValue.value = ((SoilderAgent)agent).MoveToTarget(result);
				return _returnValue;
			}
		}

		private class CMethod_SoilderAgent_TestEnemyInAtkRange : CAgentMethodBase<bool>
		{
			IInstanceMember _enemyTarget;

			public CMethod_SoilderAgent_TestEnemyInAtkRange()
			{
			}

			public CMethod_SoilderAgent_TestEnemyInAtkRange(CMethod_SoilderAgent_TestEnemyInAtkRange rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_SoilderAgent_TestEnemyInAtkRange(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_enemyTarget = AgentMeta.ParseProperty<FightAgent>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_enemyTarget != null);

				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((SoilderAgent)agent).TestEnemyInAtkRange((FightAgent)_enemyTarget.GetValueObject(self));
			}
		}

		private class CMethod_HeroAgent_IsInLootRange : CAgentMethodBase<bool>
		{
			IInstanceMember _treasure;

			public CMethod_HeroAgent_IsInLootRange()
			{
			}

			public CMethod_HeroAgent_IsInLootRange(CMethod_HeroAgent_IsInLootRange rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_HeroAgent_IsInLootRange(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_treasure = AgentMeta.ParseProperty<FightAgent>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_treasure != null);

				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((HeroAgent)agent).IsInLootRange((FightAgent)_treasure.GetValueObject(self));
			}
		}

		private class CMethod_HeroAgent_LootTreasure : CAgentMethodBase<behaviac.EBTStatus>
		{
			IInstanceMember _treasure;

			public CMethod_HeroAgent_LootTreasure()
			{
			}

			public CMethod_HeroAgent_LootTreasure(CMethod_HeroAgent_LootTreasure rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_HeroAgent_LootTreasure(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_treasure = AgentMeta.ParseProperty<FightAgent>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_treasure != null);

				Agent agent = Utils.GetParentAgent(self, _instance);

				_returnValue.value = ((HeroAgent)agent).LootTreasure((FightAgent)_treasure.GetValueObject(self));
			}

			public override IValue GetIValue(Agent self, IInstanceMember firstParam)
			{
				Agent agent = Utils.GetParentAgent(self, _instance);

				FightAgent result = ((CInstanceMember<FightAgent>)firstParam).GetValue(self);
				_returnValue.value = ((HeroAgent)agent).LootTreasure(result);
				return _returnValue;
			}
		}

		private class CMethod_HeroAgent_SetRetreatPos : CAgentMethodVoidBase
		{
			IInstanceMember _retreatPosition;

			public CMethod_HeroAgent_SetRetreatPos()
			{
			}

			public CMethod_HeroAgent_SetRetreatPos(CMethod_HeroAgent_SetRetreatPos rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_HeroAgent_SetRetreatPos(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_retreatPosition = AgentMeta.ParseProperty<bVector3>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_retreatPosition != null);

				Agent agent = Utils.GetParentAgent(self, _instance);

				((HeroAgent)agent).SetRetreatPos((bVector3)_retreatPosition.GetValueObject(self));
			}
		}


		public override bool Load()
		{
			AgentMeta.TotalSignature = 2623873306;

			AgentMeta meta;

			// behaviac.Agent
			meta = new AgentMeta(24743406);
			AgentMeta._AgentMetas_[2436498804] = meta;
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { behaviac.Agent.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// FightAgent
			meta = new AgentMeta(2912840436);
			AgentMeta._AgentMetas_[2927482685] = meta;
			meta.RegisterMemberProperty(1074892373, new CMemberProperty<bool>("couldAttack", delegate(Agent self, bool value) { ((FightAgent)self)._set_couldAttack(value); }, delegate(Agent self) { return ((FightAgent)self)._get_couldAttack(); }));
			meta.RegisterMemberProperty(1823529647, new CMemberProperty<bool>("couldMove", delegate(Agent self, bool value) { ((FightAgent)self)._set_couldMove(value); }, delegate(Agent self) { return ((FightAgent)self)._get_couldMove(); }));
			meta.RegisterMemberProperty(4050060769, new CMemberProperty<bool>("isDead", delegate(Agent self, bool value) { ((FightAgent)self)._set_isDead(value); }, delegate(Agent self) { return ((FightAgent)self)._get_isDead(); }));
			meta.RegisterMemberProperty(2799042603, new CMemberProperty<behaviac.EBTStatus>("LifeStatus", delegate(Agent self, behaviac.EBTStatus value) { ((FightAgent)self)._set_LifeStatus(value); }, delegate(Agent self) { return ((FightAgent)self)._get_LifeStatus(); }));
			meta.RegisterMemberProperty(4005016119, new CMemberProperty<bVector3>("position", delegate(Agent self, bVector3 value) { ((FightAgent)self)._set_position(value); }, delegate(Agent self) { return ((FightAgent)self)._get_position(); }));
			meta.RegisterMethod(1054489725, new CAgentMethod<bool>(delegate(Agent self) { return ((FightAgent)self).IsDead(); }));
			meta.RegisterMethod(726511973, new CAgentMethod<bool>(delegate(Agent self) { return ((FightAgent)self).IsLowHp(); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { FightAgent.LogMessage(param0); }));
			meta.RegisterMethod(181959349, new CAgentMethodVoid(delegate(Agent self) { ((FightAgent)self).PlayDead(); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// BuildingAgent
			meta = new AgentMeta(744566553);
			AgentMeta._AgentMetas_[4051970114] = meta;
			meta.RegisterMemberProperty(1074892373, new CMemberProperty<bool>("couldAttack", delegate(Agent self, bool value) { ((BuildingAgent)self)._set_couldAttack(value); }, delegate(Agent self) { return ((BuildingAgent)self)._get_couldAttack(); }));
			meta.RegisterMemberProperty(1823529647, new CMemberProperty<bool>("couldMove", delegate(Agent self, bool value) { ((BuildingAgent)self)._set_couldMove(value); }, delegate(Agent self) { return ((BuildingAgent)self)._get_couldMove(); }));
			meta.RegisterMemberProperty(4050060769, new CMemberProperty<bool>("isDead", delegate(Agent self, bool value) { ((BuildingAgent)self)._set_isDead(value); }, delegate(Agent self) { return ((BuildingAgent)self)._get_isDead(); }));
			meta.RegisterMemberProperty(2799042603, new CMemberProperty<behaviac.EBTStatus>("LifeStatus", delegate(Agent self, behaviac.EBTStatus value) { ((BuildingAgent)self)._set_LifeStatus(value); }, delegate(Agent self) { return ((BuildingAgent)self)._get_LifeStatus(); }));
			meta.RegisterMemberProperty(4005016119, new CMemberProperty<bVector3>("position", delegate(Agent self, bVector3 value) { ((BuildingAgent)self)._set_position(value); }, delegate(Agent self) { return ((BuildingAgent)self)._get_position(); }));
			meta.RegisterMethod(1054489725, new CAgentMethod<bool>(delegate(Agent self) { return ((BuildingAgent)self).IsDead(); }));
			meta.RegisterMethod(726511973, new CAgentMethod<bool>(delegate(Agent self) { return ((BuildingAgent)self).IsLowHp(); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { BuildingAgent.LogMessage(param0); }));
			meta.RegisterMethod(181959349, new CAgentMethodVoid(delegate(Agent self) { ((BuildingAgent)self).PlayDead(); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// DefenseTowerAgent
			meta = new AgentMeta(2978994066);
			AgentMeta._AgentMetas_[1520164275] = meta;
			meta.RegisterMemberProperty(1074892373, new CMemberProperty<bool>("couldAttack", delegate(Agent self, bool value) { ((DefenseTowerAgent)self)._set_couldAttack(value); }, delegate(Agent self) { return ((DefenseTowerAgent)self)._get_couldAttack(); }));
			meta.RegisterMemberProperty(1823529647, new CMemberProperty<bool>("couldMove", delegate(Agent self, bool value) { ((DefenseTowerAgent)self)._set_couldMove(value); }, delegate(Agent self) { return ((DefenseTowerAgent)self)._get_couldMove(); }));
			meta.RegisterMemberProperty(1067866206, new CMemberProperty<FightAgent>("curTarget", delegate(Agent self, FightAgent value) { ((DefenseTowerAgent)self)._set_curTarget(value); }, delegate(Agent self) { return ((DefenseTowerAgent)self)._get_curTarget(); }));
			meta.RegisterMemberProperty(4050060769, new CMemberProperty<bool>("isDead", delegate(Agent self, bool value) { ((DefenseTowerAgent)self)._set_isDead(value); }, delegate(Agent self) { return ((DefenseTowerAgent)self)._get_isDead(); }));
			meta.RegisterMemberProperty(2799042603, new CMemberProperty<behaviac.EBTStatus>("LifeStatus", delegate(Agent self, behaviac.EBTStatus value) { ((DefenseTowerAgent)self)._set_LifeStatus(value); }, delegate(Agent self) { return ((DefenseTowerAgent)self)._get_LifeStatus(); }));
			meta.RegisterMemberProperty(4005016119, new CMemberProperty<bVector3>("position", delegate(Agent self, bVector3 value) { ((DefenseTowerAgent)self)._set_position(value); }, delegate(Agent self) { return ((DefenseTowerAgent)self)._get_position(); }));
			meta.RegisterMethod(3575241253, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((DefenseTowerAgent)self).AttackCurEnemy(); }));
			meta.RegisterMethod(2972488885, new CAgentMethod<FightAgent>(delegate(Agent self) { return ((DefenseTowerAgent)self).FindEnemyInRange(); }));
			meta.RegisterMethod(1054489725, new CAgentMethod<bool>(delegate(Agent self) { return ((DefenseTowerAgent)self).IsDead(); }));
			meta.RegisterMethod(726511973, new CAgentMethod<bool>(delegate(Agent self) { return ((DefenseTowerAgent)self).IsLowHp(); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { DefenseTowerAgent.LogMessage(param0); }));
			meta.RegisterMethod(181959349, new CAgentMethodVoid(delegate(Agent self) { ((DefenseTowerAgent)self).PlayDead(); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// SoilderAgent
			meta = new AgentMeta(549697942);
			AgentMeta._AgentMetas_[4286480859] = meta;
			meta.RegisterMemberProperty(1074892373, new CMemberProperty<bool>("couldAttack", delegate(Agent self, bool value) { ((SoilderAgent)self)._set_couldAttack(value); }, delegate(Agent self) { return ((SoilderAgent)self)._get_couldAttack(); }));
			meta.RegisterMemberProperty(1823529647, new CMemberProperty<bool>("couldMove", delegate(Agent self, bool value) { ((SoilderAgent)self)._set_couldMove(value); }, delegate(Agent self) { return ((SoilderAgent)self)._get_couldMove(); }));
			meta.RegisterMemberProperty(593809957, new CMemberProperty<ActionStatus>("curActionStatus", delegate(Agent self, ActionStatus value) { ((SoilderAgent)self)._set_curActionStatus(value); }, delegate(Agent self) { return ((SoilderAgent)self)._get_curActionStatus(); }));
			meta.RegisterMemberProperty(2679270583, new CMemberProperty<FightAgent>("curEnemyTarget", delegate(Agent self, FightAgent value) { ((SoilderAgent)self)._set_curEnemyTarget(value); }, delegate(Agent self) { return ((SoilderAgent)self)._get_curEnemyTarget(); }));
			meta.RegisterMemberProperty(1428937743, new CMemberProperty<Situation>("curSituation", delegate(Agent self, Situation value) { ((SoilderAgent)self)._set_curSituation(value); }, delegate(Agent self) { return ((SoilderAgent)self)._get_curSituation(); }));
			meta.RegisterMemberProperty(1608869297, new CMemberProperty<bVector3>("curTacticAtkPos", delegate(Agent self, bVector3 value) { ((SoilderAgent)self)._set_curTacticAtkPos(value); }, delegate(Agent self) { return ((SoilderAgent)self)._get_curTacticAtkPos(); }));
			meta.RegisterMemberProperty(4009490894, new CMemberProperty<bVector3>("homePoint", delegate(Agent self, bVector3 value) { ((SoilderAgent)self)._set_homePoint(value); }, delegate(Agent self) { return ((SoilderAgent)self)._get_homePoint(); }));
			meta.RegisterMemberProperty(4050060769, new CMemberProperty<bool>("isDead", delegate(Agent self, bool value) { ((SoilderAgent)self)._set_isDead(value); }, delegate(Agent self) { return ((SoilderAgent)self)._get_isDead(); }));
			meta.RegisterMemberProperty(2799042603, new CMemberProperty<behaviac.EBTStatus>("LifeStatus", delegate(Agent self, behaviac.EBTStatus value) { ((SoilderAgent)self)._set_LifeStatus(value); }, delegate(Agent self) { return ((SoilderAgent)self)._get_LifeStatus(); }));
			meta.RegisterMemberProperty(4005016119, new CMemberProperty<bVector3>("position", delegate(Agent self, bVector3 value) { ((SoilderAgent)self)._set_position(value); }, delegate(Agent self) { return ((SoilderAgent)self)._get_position(); }));
			meta.RegisterMethod(3127879122, new CMethod_SoilderAgent_Attack());
			meta.RegisterMethod(1629954219, new CAgentMethodVoid<bVector3>(delegate(Agent self, bVector3 task_pos) { }) /* AttackToPos_task */);
			meta.RegisterMethod(783803240, new CAgentMethodVoid<FightAgent>(delegate(Agent self, FightAgent task_chaseTarget) { }) /* ChaseAndAttack_task */);
			meta.RegisterMethod(2716570482, new CAgentMethod<FightAgent>(delegate(Agent self) { return ((SoilderAgent)self).GetNearestEnemy(); }));
			meta.RegisterMethod(2253404977, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((SoilderAgent)self).Idle(); }));
			meta.RegisterMethod(1054489725, new CAgentMethod<bool>(delegate(Agent self) { return ((SoilderAgent)self).IsDead(); }));
			meta.RegisterMethod(726511973, new CAgentMethod<bool>(delegate(Agent self) { return ((SoilderAgent)self).IsLowHp(); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { SoilderAgent.LogMessage(param0); }));
			meta.RegisterMethod(2754924504, new CMethod_SoilderAgent_MoveTo());
			meta.RegisterMethod(1793645156, new CMethod_SoilderAgent_MoveToTarget());
			meta.RegisterMethod(181959349, new CAgentMethodVoid(delegate(Agent self) { ((SoilderAgent)self).PlayDead(); }));
			meta.RegisterMethod(3970781763, new CMethod_SoilderAgent_TestEnemyInAtkRange());
			meta.RegisterMethod(3756619215, new CAgentMethod<bool>(delegate(Agent self) { return ((SoilderAgent)self).TestHasAtkToPosCommand(); }));
			meta.RegisterMethod(700275576, new CAgentMethod<bool>(delegate(Agent self) { return ((SoilderAgent)self).TestHasEnemyInEyeRange(); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// HeroAgent
			meta = new AgentMeta(3064835767);
			AgentMeta._AgentMetas_[2270112014] = meta;
			meta.RegisterMemberProperty(1074892373, new CMemberProperty<bool>("couldAttack", delegate(Agent self, bool value) { ((HeroAgent)self)._set_couldAttack(value); }, delegate(Agent self) { return ((HeroAgent)self)._get_couldAttack(); }));
			meta.RegisterMemberProperty(1823529647, new CMemberProperty<bool>("couldMove", delegate(Agent self, bool value) { ((HeroAgent)self)._set_couldMove(value); }, delegate(Agent self) { return ((HeroAgent)self)._get_couldMove(); }));
			meta.RegisterMemberProperty(593809957, new CMemberProperty<ActionStatus>("curActionStatus", delegate(Agent self, ActionStatus value) { ((HeroAgent)self)._set_curActionStatus(value); }, delegate(Agent self) { return ((HeroAgent)self)._get_curActionStatus(); }));
			meta.RegisterMemberProperty(2679270583, new CMemberProperty<FightAgent>("curEnemyTarget", delegate(Agent self, FightAgent value) { ((HeroAgent)self)._set_curEnemyTarget(value); }, delegate(Agent self) { return ((HeroAgent)self)._get_curEnemyTarget(); }));
			meta.RegisterMemberProperty(1428937743, new CMemberProperty<Situation>("curSituation", delegate(Agent self, Situation value) { ((HeroAgent)self)._set_curSituation(value); }, delegate(Agent self) { return ((HeroAgent)self)._get_curSituation(); }));
			meta.RegisterMemberProperty(1608869297, new CMemberProperty<bVector3>("curTacticAtkPos", delegate(Agent self, bVector3 value) { ((HeroAgent)self)._set_curTacticAtkPos(value); }, delegate(Agent self) { return ((HeroAgent)self)._get_curTacticAtkPos(); }));
			meta.RegisterMemberProperty(3679778246, new CMemberProperty<bVector3>("fleePos", delegate(Agent self, bVector3 value) { ((HeroAgent)self)._set_fleePos(value); }, delegate(Agent self) { return ((HeroAgent)self)._get_fleePos(); }));
			meta.RegisterMemberProperty(4009490894, new CMemberProperty<bVector3>("homePoint", delegate(Agent self, bVector3 value) { ((HeroAgent)self)._set_homePoint(value); }, delegate(Agent self) { return ((HeroAgent)self)._get_homePoint(); }));
			meta.RegisterMemberProperty(4050060769, new CMemberProperty<bool>("isDead", delegate(Agent self, bool value) { ((HeroAgent)self)._set_isDead(value); }, delegate(Agent self) { return ((HeroAgent)self)._get_isDead(); }));
			meta.RegisterMemberProperty(2799042603, new CMemberProperty<behaviac.EBTStatus>("LifeStatus", delegate(Agent self, behaviac.EBTStatus value) { ((HeroAgent)self)._set_LifeStatus(value); }, delegate(Agent self) { return ((HeroAgent)self)._get_LifeStatus(); }));
			meta.RegisterMemberProperty(4005016119, new CMemberProperty<bVector3>("position", delegate(Agent self, bVector3 value) { ((HeroAgent)self)._set_position(value); }, delegate(Agent self) { return ((HeroAgent)self)._get_position(); }));
			meta.RegisterMemberProperty(1022875399, new CMemberProperty<bVector3>("retreatPos", delegate(Agent self, bVector3 value) { ((HeroAgent)self)._set_retreatPos(value); }, delegate(Agent self) { return ((HeroAgent)self)._get_retreatPos(); }));
			meta.RegisterMethod(2674554263, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).ArrivedRetreatPos(); }));
			meta.RegisterMethod(3127879122, new CMethod_SoilderAgent_Attack());
			meta.RegisterMethod(1629954219, new CAgentMethodVoid<bVector3>(delegate(Agent self, bVector3 task_pos) { }) /* AttackToPos_task */);
			meta.RegisterMethod(3981281435, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((HeroAgent)self).CallFriendHeroToHealMe(); }));
			meta.RegisterMethod(783803240, new CAgentMethodVoid<FightAgent>(delegate(Agent self, FightAgent task_chaseTarget) { }) /* ChaseAndAttack_task */);
			meta.RegisterMethod(1105002646, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((HeroAgent)self).CombooKill(); }));
			meta.RegisterMethod(143620965, new CAgentMethodVoid<bVector3>(delegate(Agent self, bVector3 task_cooperatePos) { }) /* Cooperate_task */);
			meta.RegisterMethod(592004963, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).CouldBeSecKilled(); }));
			meta.RegisterMethod(1497521703, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).CouldUseQuickHeal(); }));
			meta.RegisterMethod(2027654893, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).CouldUseSlowHeal(); }));
			meta.RegisterMethod(1787278696, new CAgentMethod<bVector3>(delegate(Agent self) { return ((HeroAgent)self).GetCurReseanableTacticsTarget(); }));
			meta.RegisterMethod(749487724, new CAgentMethod<float>(delegate(Agent self) { return ((HeroAgent)self).GetDistanceFromHome(); }));
			meta.RegisterMethod(1218032045, new CAgentMethod<int>(delegate(Agent self) { return ((HeroAgent)self).GetEnemyCountInRange(); }));
			meta.RegisterMethod(2743497259, new CAgentMethod<int>(delegate(Agent self) { return ((HeroAgent)self).GetEnemyHeroCountInRange(); }));
			meta.RegisterMethod(3513837595, new CAgentMethod<int>(delegate(Agent self) { return ((HeroAgent)self).GetFirendHeroCountInRange(); }));
			meta.RegisterMethod(3164054455, new CAgentMethod<int>(delegate(Agent self) { return ((HeroAgent)self).GetFriendCountInRange(); }));
			meta.RegisterMethod(2716570482, new CAgentMethod<FightAgent>(delegate(Agent self) { return ((HeroAgent)self).GetNearestEnemy(); }));
			meta.RegisterMethod(1237488994, new CAgentMethod<FightAgent>(delegate(Agent self) { return ((HeroAgent)self).GetWeakestEnemy(); }));
			meta.RegisterMethod(2569706439, new CAgentMethod<FightAgent>(delegate(Agent self) { return ((HeroAgent)self).GetWeakHeroInRange(); }));
			meta.RegisterMethod(2547311622, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).HasCombooKill(); }));
			meta.RegisterMethod(1496859174, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).HasEnemyInEyeRange(); }));
			meta.RegisterMethod(996104106, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).HasReturnHomeSkill(); }));
			meta.RegisterMethod(1519838893, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).HasTreasureInEyeRange(); }));
			meta.RegisterMethod(2253404977, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((HeroAgent)self).Idle(); }));
			meta.RegisterMethod(1054489725, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).IsDead(); }));
			meta.RegisterMethod(2432849062, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).IsEnemyChasing(); }));
			meta.RegisterMethod(1778583587, new CMethod_HeroAgent_IsInLootRange());
			meta.RegisterMethod(726511973, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).IsLowHp(); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { HeroAgent.LogMessage(param0); }));
			meta.RegisterMethod(3468933412, new CMethod_HeroAgent_LootTreasure());
			meta.RegisterMethod(762819242, new CAgentMethodVoid<FightAgent>(delegate(Agent self, FightAgent task_treasure) { }) /* LootTreasure_task */);
			meta.RegisterMethod(2754924504, new CMethod_SoilderAgent_MoveTo());
			meta.RegisterMethod(1793645156, new CMethod_SoilderAgent_MoveToTarget());
			meta.RegisterMethod(181959349, new CAgentMethodVoid(delegate(Agent self) { ((HeroAgent)self).PlayDead(); }));
			meta.RegisterMethod(2057619381, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((HeroAgent)self).QuickHeal(); }));
			meta.RegisterMethod(4056496344, new CMethod_HeroAgent_SetRetreatPos());
			meta.RegisterMethod(563297901, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((HeroAgent)self).SkillReturnHome(); }));
			meta.RegisterMethod(420198528, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((HeroAgent)self).SlowHealSelf(); }));
			meta.RegisterMethod(2783913227, new CAgentMethodVoid<bVector3>(delegate(Agent self, bVector3 task_tacticsAtkPos) { }) /* TacticsAttack_task */);
			meta.RegisterMethod(3500369013, new CAgentMethodVoid<bVector3>(delegate(Agent self, bVector3 task_RetreatPos) { }) /* TempRetreat_task */);
			meta.RegisterMethod(2100968353, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).TestArrivedTacticsTarget(); }));
			meta.RegisterMethod(2854910934, new CAgentMethod<Situation>(delegate(Agent self) { return ((HeroAgent)self).TestCurSituation(); }));
			meta.RegisterMethod(3970781763, new CMethod_SoilderAgent_TestEnemyInAtkRange());
			meta.RegisterMethod(982139696, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).TestFriendHeroCouldHealMe(); }));
			meta.RegisterMethod(3756619215, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).TestHasAtkToPosCommand(); }));
			meta.RegisterMethod(700275576, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).TestHasEnemyInEyeRange(); }));
			meta.RegisterMethod(3000592579, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).TestHasTacticsTargetLeft(); }));
			meta.RegisterMethod(1819711739, new CAgentMethod<bool>(delegate(Agent self) { return ((HeroAgent)self).TestSomeEnemyHeroCouldBeKilled(); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			AgentMeta.Register<behaviac.Agent>("behaviac.Agent");
			AgentMeta.Register<FightAgent>("FightAgent");
			AgentMeta.Register<BuildingAgent>("BuildingAgent");
			AgentMeta.Register<DefenseTowerAgent>("DefenseTowerAgent");
			AgentMeta.Register<SoilderAgent>("SoilderAgent");
			AgentMeta.Register<HeroAgent>("HeroAgent");
			AgentMeta.Register<Situation>("Situation");
			ComparerRegister.RegisterType<Situation, CompareValue_Situation>();
			AgentMeta.Register<ActionStatus>("ActionStatus");
			ComparerRegister.RegisterType<ActionStatus, CompareValue_ActionStatus>();
			AgentMeta.Register<bVector3>("bVector3");
			ComparerRegister.RegisterType<bVector3, CompareValue_bVector3>();
			return true;
		}

		public override bool UnLoad()
		{
			AgentMeta.UnRegister<behaviac.Agent>("behaviac.Agent");
			AgentMeta.UnRegister<FightAgent>("FightAgent");
			AgentMeta.UnRegister<BuildingAgent>("BuildingAgent");
			AgentMeta.UnRegister<DefenseTowerAgent>("DefenseTowerAgent");
			AgentMeta.UnRegister<SoilderAgent>("SoilderAgent");
			AgentMeta.UnRegister<HeroAgent>("HeroAgent");
			AgentMeta.UnRegister<Situation>("Situation");
			AgentMeta.UnRegister<ActionStatus>("ActionStatus");
			AgentMeta.UnRegister<bVector3>("bVector3");
			return true;
		}
	}
}
