// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// -------------------
// Customized enums
// -------------------

public enum Situation
{
	Advantage = 1,
	Disadvantage = 2,
	CantTell = 3,
}

// -------------------
// Customized structs
// -------------------

public class bVector3
{
    public float x;
    public float y;
    public float z;
    public bVector3() { }
    public bVector3(float x, float y, float z) {
        this.x = x;
        this.y = y;
        this.z = z;
    }
}

public enum ActionStatus
{
    Moving = 1,
    StopAndDoingNothing = 2,
    StopAndDoingSomething = 3,
}

public static class bVector3Extension {
    public static Vector3 UnityVec(this bVector3 bVector)
    {
        return new Vector3(bVector.x, bVector.y, bVector.z);
    }
}
